name = "crashalert"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
[vars]
CRASH_ALERT_PRICE_ID_BASIC="price_1Sv59HGXCHuavzV6AsejQbSC"
CRASH_ALERT_PRICE_ID_PRO="price_1Sv59kGXCHuavzV6UnPJc0JM"
CRASH_ALERT_PRICE_ID_ADVANCED="price_1Sv5BGGXCHuavzV6Hl4nZhCZ"
NEXT_PUBLIC_URL="https://crashalert.online"
